apiVersion: v1
kind: Pod
metadata:
  name: customer-pod
  # namespace: projecta
  labels:
    app: packersmovers    
spec:
  containers:
  - name: customer
    image: 851271747310.dkr.ecr.us-east-2.amazonaws.com/customer:1
    ports:
    - containerPort: 8080
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m" 
  - name: webapp
    image: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m" 
